name: pnpm.lint
description: Linting projects

inputs:
  working-directory:
    description: Working directory
    required: true

runs:
  using: composite
  steps:
    - name: Lint
      run: pnpm lint
      shell: bash
      working-directory: ${{ working-directory }}