name: dotnet.nuget.pack
description: Packing NuGet package.

inputs:
  solution:
    description: Solution name
    required: true

runs:
  using: composite
  steps:
    - name: Packing NuGet Packages
      run: dotnet pack --artifacts-path ${{ github.workspace}}/artifacts --output ${{ github.workspace}}/artifacts -p:Version=0.0.0-dev.1 ${{ inputs.solution }}
      shell: bash
