name: sonar.begin
description: Begin SonarCloud analysis

inputs:
  project_key:
    description: SonarQube project key
    required: true
  token:
    description: SonarQube token
    required: true

runs:
  using: composite
  steps:
    - name: Begin Analysis
      shell: bash
      run: ${{ runner.temp }}\scanner\dotnet-sonarscanner begin /k:"${{ inputs.project_key }}" /o:"ironyxlabs" /d:sonar.token="${{ inputs.token }}"
