name: sonar.init
description: End SonarCloud analysis

runs:
  using: composite
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: "zulu"

    - name: Cache SonarQube Cloud packages
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache SonarQube Cloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ runner.temp }}\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner

    - name: Install SonarQube Cloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        New-Item -Path ${{ runner.temp }}\scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path ${{ runner.temp }}\scanner
