on:
  workflow_call:

jobs:
  restore-dependencies:
    runs-on: ubuntu-latest

    outputs:
      cache_key: ${{ steps.dependencies.outputs.cache_key }}

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4

      - name: Restore Dependencies
        id: dependencies
        uses: IronyxLabs/ironyx-scripts/.github/actions/dotnet/restore-dependencies@chore/1-create-ci-workflow-for-net-applications

  build:
    needs: [restore-dependencies]
    runs-on: ubuntu-latest

    outputs:
      cache_key: ${{ steps.build.outputs.artifact_key }}

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4

      - name: Build
        id: build
        uses: IronyxLabs/ironyx-scripts/.github/actions/dotnet/build@chore/1-create-ci-workflow-for-net-applications
        with:
          cache_key: ${{ needs.restore-dependencies.outputs.cache_key }}

  test:
    needs: [restore-dependencies, build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v4

      - name: Execute Tests
        id: test
        uses: IronyxLabs/ironyx-scripts/.github/actions/dotnet/test@chore/1-create-ci-workflow-for-net-applications
        with:
          artifact_key: ${{ needs.build.outputs.artifact_key }}
