on:
  workflow_call:
    secrets:
      nuget-api_key:
        description: NuGet Artifactory token
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v4
        with:
          name: artifacts_${{ github.event.workflow_run.id }}

      - name: Publish NuGet Packages
        id: publish
        uses: IronyxLabs/ironyx-scripts/.github/actions/dotnet/publish-nuget@feature/6-create-nuget-release-pipeline
        with:
          api_key: ${{ secrets.nuget-api_key }}
