on:
  workflow_call:
    secrets:     
      github-token:
        description: GitHub token
        required: true

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v7
        with:
          name: artifacts
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.github-token }}

      - name: Publish
        id: publish
        uses: IronyxLabs/ironyx-scripts/.github/actions/pnpm/publish@feature/13-create-cd-pipeline-for-svelte-package
        with:
          token: ${{ secrets.github-token }}
