name: Sample CI

on:
  pull_request:
    branches:
      - main
      - develop
      - release/*
  workflow_dispatch:

run-name: ${{ github.event_name == 'pull_request' && format('[PR]{0}', github.event.pull_request.title) || format('[MANUAL]Run on {0} branch', github.ref_name) }}

jobs:
  ci:
    uses: IronyxLabs/ironyx-scripts/.github/workflows/dotnet_ci-pipeline.yaml@chore/1-create-ci-workflow-for-net-applications
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      testspace-token: ${{ secrets.TESTSPACE_TOKEN }}
    with:
      sonar-project_key: IronyxLabs_ironyx-scripts
