name: Sample CI

on:
  workflow_dispatch:

jobs:
  ci:
    uses: IronyxLabs/ironyx-scripts/.github/workflows/dotnet_ci-pipeline.yaml@chore/1-create-ci-workflow-for-net-applications
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      testspace-token: ${{ secrets.TESTSPACE_TOKEN }}
    with:
      sonar-project_key: IronyxLabs_ironyx-scripts
