name: Sample NuGet CD

run-name: "[RELEASE] - Publish NuGet Packages"

on:
  workflow_run:
    workflows: ["Sample NuGet CI"]
    types: [completed]

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v7
        with:
          name: artifacts_${{ github.event.workflow_run.id }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Publish NuGet Packages
        id: publish
        uses: IronyxLabs/ironyx-scripts/.github/actions/dotnet/publish-nuget@feature/6-create-nuget-release-pipeline
        with:
          api_key: ${{ secrets.NUGET_API_KEY }}
