name: Sample NuGet CD

run-name: "[RELEASE] - Publish NuGet Packages"

on:
  workflow_run:
    workflows:
      - "Sample NuGet CI"
    types: [completed]

jobs:
  ci:
    uses: IronyxLabs/ironyx-scripts/.github/workflows/dotnet_nuget_cd-pipeline.yaml@feature/6-create-nuget-release-pipeline
    secrets:
      nuget-api_key: ${{ secrets.NUGET_API_KEY }}
