on:
  workflow_call:
    secrets:      
      testspace-token:
        description: TestSpace token
        required: true
    inputs:
      working-directory:
        description: Working directory. Default is src
        type: string
        default: src

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v6
      
      - name: Setup pnpm
        id: setup-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: ${{ inputs.working-directory }}/pnpm-lock.yaml

      - name: Install Dependencies
        uses: IronyxLabs/ironyx-scripts/.github/actions/pnpm/install@feature/12-create-ci-pipeline-for-svelte
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: Lint
        uses: IronyxLabs/ironyx-scripts/.github/actions/pnpm/lint@feature/12-create-ci-pipeline-for-svelte
        with:
          working-directory: ${{ inputs.working-directory }}
  
      - name: Test
        uses: IronyxLabs/ironyx-scripts/.github/actions/pnpm/test@feature/12-create-ci-pipeline-for-svelte
        with:
          working-directory: ${{ inputs.working-directory }}
          token: ${{ secrets.testspace-token }}
      